---
apiVersion: v1
kind: Secret
metadata:
  name: sandesh-secret
type: Opaque
stringData:
  # Basic auth users here:
  basic.txt: |
    ICNHUQ7MFLRRYC6K: uHrrjpfrWJCv02Q4XuWycZpPy4AoUe5sn7f0uur06TFtKKHtvaur/xJ7cyyjns3p,krp-users
    bob: bobsecret,krp-users

  # Kafka Rest block is for Basic Auth
  # Kafka Client block is for propogation, make sure all basic auth users are ALSO defined in KafkaClient
  # bob/bobsecret will not work as the user does not exist in Confluent cloud.
  # bob is a valid user for REST proxy frontend but cannot see anything on kafka cluster.
  restProxyUsers.jaas: |
    KafkaRest {
        org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
        debug="true"
        file="/mnt/secrets/sandesh-secret/basic.txt";
    };


    KafkaClient {
      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="ICNHUQ7MFLRRYC6K"
      password="uHrrjpfrWJCv02Q4XuWycZpPy4AoUe5sn7f0uur06TFtKKHtvaur/xJ7cyyjns3p";

      org.apache.kafka.common.security.plain.PlainLoginModule required
      username="bob"
      password="bobsecret";
    };
